server:
  port: 5001
spring:
  application:
    name: newsnews-app-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.86.130:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE
      routes:
      # 文章微服务路由设置
      - id: newsnews-article
        uri: lb://newsnews-article
        predicates:
        - Path=/article/**
        filters:
        - StripPrefix= 1
      # 用户微服务路由设置
      - id: newsnews-user
          uri: lb://newsnews-user
          predicates:
          - Path=/user/**
          filters:
          - StripPrefix= 1