server:
  port: 9003
spring:
  application:
    name: newsnews-article
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.86.130:8848
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}_tx_group
  # kafka配置
  kafka:
    bootstrap-servers: 192.168.86.130:9092
    consumer:
      group-id: ${spring.application.name}-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.86.130:3307/newsnews_article?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.light.model.article.pojos
  # 配置数据中心id和机器id
  global-config:
    datacenter-id: 1
    worker-id: 1
# 图片访问ip，添加自定义的图片访问ip
fdfs:
  url: http://192.168.86.130/
# 自定义elasticsearch连接配置
elasticsearch:
  host: 118.25.197.221
  port: 9200