server:
  port: 9011
spring:
  application:
    name: newsnews-admin
  # kafka配置
  kafka:
    bootstrap-servers: 192.168.86.130:9092
    consumer:
      group-id: ${spring.application.name}-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.86.130:3307/newsnews_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.86.130:8848
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}_tx_group

  # redis配置
  redis:
    host: 192.168.86.130
    port: 6379

# 设置全局Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.light.model.admin.pojos

# 图片访问ip，添加自定义的图片访问ip
fdfs:
  url: http://192.168.86.130/

# xxljob分布式任务调度平台配置
xxljob:
  admin:
    addresses: http://192.168.86.130:9080/xxl-job-admin
  executor:
    appname: newsnews-admin-executor
    port: 9999