#全局端口定义server:
# 全局字符集设置
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  aop:
    proxy-target-class: true
  data:
    mongodb:
      host: 192.168.86.130
      port: 27017
      dbname: newsnews-comment
server:
  tomcat:
    uri-encoding: utf-8
